# Start from a base Microsoft-provided image. 
# This one includes Python, Node.js, and other common tools.
# You can find many other options to start from.
FROM mcr.microsoft.com/devcontainers/universal:2

# You can add any other tools your students need here.
# For example, to install Python libraries:
# RUN pip3 install pandas numpy